from selenium.webdriver.common.by import By

class Locators:
    LK_BUTTON_MAIN = (By.XPATH,".//p[text()='Личный Кабинет']")
    REGISTER_BUTTON = (By.XPATH,".//a[text()='Зарегистрироваться']")
    NAME_INPUT_REG = (By.XPATH, ".//label[text()='Имя']/../input")
    EMAIL_INPUT_REG = (By.XPATH,".//label[text()='Email']/../input")
    PASSWORD_INPUT_REG = (By.XPATH, ".//input[@name='Пароль']")
    ENTER_BUTTON = (By.XPATH,".//button[text()='Войти']")
    REGISTER_BUTTON_REG = (By.XPATH, ".//button[text()='Зарегистрироваться']")
    INCORRECT_PASSWORD_REG = (By.XPATH, ".//p[text()='Некорректный пароль']")
    LOGIN_BUTTON_MAIN = (By.XPATH,".//button[text()='Войти в аккаунт']")
    SIGN_IN_BUTTON = (By.XPATH,".//button[text()='Войти']")
    SIGN_IN_BUTTON_REG = (By.XPATH,".//a[text()='Войти']")
    RESET_PASS_BUTTON = (By.XPATH,".//a[text()='Восстановить пароль']")
    RESET_BUTTON = (By.XPATH,".//button[text()='Восстановить']")
    RESET_CODE_INPUT = (By.XPATH,".//label[text()='Введите код из письма']/../input")
    CONSTRUCTOR = (By.XPATH, ".//p[text()='Конструктор']")
    LOGO = (By.CLASS_NAME,'AppHeader_header__logo__2D0X2')
    LOGOUT = (By.XPATH,".//button[text()='Выход']")
    SAUCE = (By.XPATH,".//span[text()='Соусы']")
    SAUCE_PARENT = (By.XPATH, ".//span[text()='Соусы']//parent::div[@class = 'tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect']")
    STUFFING = (By.XPATH,".//span[text()='Начинки']")
    STUFFING_PARENT = (By.XPATH, ".//span[text()='Начинки']//parent::div[@class = 'tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect']")
    ROLL = (By.XPATH,".//span[text()='Булки']")
    ROLL_PARENT = (By.XPATH, ".//span[text()='Булки']//parent::div[@class = 'tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect']")